# Generated by Django 3.2 on 2021-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=30)),
                ('barangay', models.CharField(max_length=30)),
                ('streetname', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('vaccinename', models.CharField(max_length=30)),
            ],
        ),
    ]
